doctrine:
    dbal:
        dbname: '%env(DB_NAME)%'
        user: '%env(DB_USERNAME)%'
        password: '%env(DB_PASSWORD)%'
        charset: utf8

        types:
            UserRole: Athorrent\Database\Type\UserRole

    orm:
        auto_mapping: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        mappings:
            Athorrent:
                type: annotation
                dir: '%kernel.project_dir%/src/Database/Entity'
                prefix: Athorrent\Database\Entity
                is_bundle: false
