phpfastcache:
    twig_driver: 'default' # This option must be a valid declared driver, in our example: "filecache"
    twig_block_debug: false # This option will wrap CACHE/ENDCACHE blocks with block debug as HTML comment

    drivers:
        default:
            type: Apcu
            parameters:
